carlton

Sakshi as the error says itâ€™s unable to find your file. Try adding a . (dot) before the location.

sir i have used the dot(.) while sending the request to postman in the query which i provided to the task. Is the dot(.) should be added somewhere else?

If you have added that dot as a prefix to your locations then, you would have to structure your query_gpt in such a way that it takes these dots into consideration.

sir i have tried that by putting by doing this import os
from dotenv import load_dotenv
import json
import requests
from dateutil import parser as date_parser
from sklearn.metrics.pairwise import cosine_similarity
from fastapi import FastAPI, HTTPException
from fastapi.middleware.cors import CORSMiddleware
import pandas as pd
from fastapi.responses import StreamingResponse, JSONResponse
from typing import Dict, Any, List
import subprocess
import datetime
from pathlib import Path
import sqlite3
import base64
import mimetypes
import numpy as np

app = FastAPI()

app.a

---

